rem Licensed Materials - Property of IBM
rem 5725A15, 5724R81
rem (c) Copyright IBM Corp. 2010, 2011  All Rights Reserved.
rem US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
rem
echo ====================
echo "Installing installer-name ..." or "Configuring module-name ..." etc.
time /t

set PBSDB2="C:"

echo Creating Content Engine GCD database, tablespace, and granting proper rights to gcddbuser ...
db2 CREATE DATABASE GCD_DB AUTOMATIC STORAGE YES  ON '%PBSDB2%\' DBPATH ON '%PBSDB2%\' USING CODESET UTF-8 TERRITORY US COLLATE USING SYSTEM PAGESIZE 32768
db2 CONNECT TO GCD_DB
db2 CREATE  REGULAR  TABLESPACE GCD_TS PAGESIZE 32 K  MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 16 OVERHEAD 10.5 PREFETCHSIZE 16 TRANSFERRATE 0.14 BUFFERPOOL  IBMDEFAULTBP  DROPPED TABLE RECOVERY ON
db2 GRANT  CREATETAB,CONNECT ON DATABASE  TO USER GCDDBUSER
db2 GRANT USE OF TABLESPACE GCD_TS TO USER GCDDBUSER
db2 CONNECT RESET
time /t
echo --------------------

echo Creating Content Engine sample Object Store database, tablespaces, and granting proper rights to osdbuser ...
db2 CREATE DATABASE OS_DB AUTOMATIC STORAGE YES  ON '%PBSDB2%\' DBPATH ON '%PBSDB2%\' USING CODESET UTF-8 TERRITORY US COLLATE USING SYSTEM PAGESIZE 32768
db2 CONNECT TO OS_DB
db2 CREATE  REGULAR  TABLESPACE CEDATA_TS PAGESIZE 32 K  MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 16 OVERHEAD 10.5 PREFETCHSIZE 16 TRANSFERRATE 0.14 BUFFERPOOL  IBMDEFAULTBP  DROPPED TABLE RECOVERY ON
db2 CREATE  USER TEMPORARY  TABLESPACE USRTEMP_TS PAGESIZE 32 K  MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 16 OVERHEAD 10.5 PREFETCHSIZE 16 TRANSFERRATE 0.14 BUFFERPOOL  IBMDEFAULTBP
db2 GRANT  CREATETAB,CONNECT ON DATABASE  TO USER OSDBUSER
db2 GRANT USE OF TABLESPACE CEDATA_TS TO USER OSDBUSER
db2 GRANT USE OF TABLESPACE USRTEMP_TS TO USER OSDBUSER
db2 CREATE  REGULAR  TABLESPACE PEDATA_TS PAGESIZE 32 K  MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 16 OVERHEAD 10.5 PREFETCHSIZE 16 TRANSFERRATE 0.14 BUFFERPOOL  IBMDEFAULTBP  DROPPED TABLE RECOVERY ON
db2 GRANT  SECADM ON DATABASE  TO USER OSDBUSER
db2 grant use of tablespace pedata_ts to user OSDBUSER
db2 UPDATE DATABASE CONFIGURATION USING APPLHEAPSZ 2560 IMMEDIATE
db2 CONNECT RESET
time /t
echo --------------------

